name: Lint + Test
on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install packages
        run: |
          pip install -r aggregate/requirements-dev.txt
          pip install -r aggregate/requirements.txt
          pip install -r gcp_cost_control/requirements.txt
          pip install -r gcp_cost_report/requirements.txt

      - name: pre-commit
        run: pre-commit run --all-files

      - name: "Run doctests"
        run: |
          pytest \
            -v \
            --doctest-modules \
            --ignore gcp_cost_control \
            --ignore gcp_cost_report \
            --ignore aggregate/__main__.py \
            --ignore aggregate/main.py \
            --ignore aggregate/local.py

