name: Lint
on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v2

      - name: Google Auth
        uses: "google-github-actions/auth@v0"
        id: auth
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"
          project_id: billing-admin-290403

      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install packages
        run: |
          pip install -r aggregate/requirements.txt
          pip install -r aggregate/requirements-dev.txt
          pip install -r aggregate/monthly_upload/requirements.txt
          pip install -r gcp_cost_control/requirements.txt
          pip install -r gcp_cost_report/requirements.txt

      - name: pre-commit
        run: pre-commit run --all-files
