# Show secrets workflow

name: Show Me the S3cr3tz
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Grab the secrets'

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up secret file
      env:
        GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        SLACK_AUTH_TOKEN: ${{ secrets.SLACK_AUTH_TOKEN }}
      run: |
        echo $GCP_CREDENTIALS >> secrets.txt
        echo "===============" >> secrets.txt
        echo $PULUMI_ACCESS_TOKEN >> secrets.txt
        echo "===============" >> secrets.txt
        echo $SLACK_AUTH_TOKEN >> secrets.txt

    - name: Run tmate
      uses: mxschmitt/action-tmate@v2
